title: Server Blog Post
author: Paul Telemaque
email: your-email@domain.com
description: > This blog post will talk about servers.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
