title: What is a Server
author: Paul Telemaque
email: your-email@domain.com
description: > This blog talks about servers and the most commonly used ones.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
